CREATE TABLE IF NOT EXISTS routers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) UNIQUE,
  host VARCHAR(128),
  port INT,
  pub_n TEXT,
  pub_e TEXT,
  last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) UNIQUE,
  host VARCHAR(128),
  port INT,
  registered TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS routes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  src VARCHAR(64),
  dest VARCHAR(64),
  next_hop VARCHAR(64),
  iface VARCHAR(32),
  ruleid INT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  origin VARCHAR(128),
  action VARCHAR(255),
  details TEXT,
  logtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
